name: Android aarch64 APK

on:
  workflow_dispatch:

jobs:
  apk:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Mark git directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install dependencies
        run: |
          sudo ./ide/provisioning/install-debian-packages.sh UPDATE
          sudo ./ide/provisioning/install-debian-packages.sh BASE
          sudo ./ide/provisioning/install-debian-packages.sh LINUX
          sudo ./ide/provisioning/install-debian-packages.sh ARM
          sudo ./ide/provisioning/install-debian-packages.sh LLVM
          sudo ./ide/provisioning/install-debian-packages.sh ANDROID
          sudo ./ide/provisioning/install-android-tools.sh NDK
          sudo ./ide/provisioning/install-android-tools.sh SDK
          sudo ./ide/provisioning/install-debian-packages.sh CLEAN

      - name: Build arm64 APK
        run: make -j$(nproc) TARGET=ANDROIDAARCH64 DEBUG=y USE_CCACHE=y V=2 output/ANDROID/bin/XCSoar.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: XCSoar-aarch64
          path: output/ANDROID/bin/XCSoar*.apk
          if-no-files-found: error
